### ISSUE TITLE
AbiJson Type 'AbiJson' does not conform to protocol 'Encodable'

### ISSUE THREAD

**Issue by zhenghongchuan** [ProChain/SwiftyEOS#12]
@objcMembers class AbiJson: NSObject, Encodable {
    var code: String
    var action: String
    var args: Dictionary<String, AnyCodable>
    
    init(code: String, action: String, json: String) throws {
        self.code = code
        self.action = action
        
        let decoder = JSONDecoder()
        self.args = try decoder.decode([String: AnyCodable].self, from: json.data(using: .utf8)!)
    }
}

**Comment by croath** [comment]
Hi @zhenghongchuan ,

Thanks for your feedback.

What target were you building on? The SwiftyEOS or SwiftyEOS-iOS-Example? Or in your own app?

Can you pull the latest code and try that again because I've made some updates yesterday.

**Comment by croath** [comment]
And make sure the Swift version is set to 4.1.

**Comment by zhenghongchuan** [comment]
This Code is in Transaction.swift. My project is written in OC. Swift version has set to 4.1

**Comment by zhenghongchuan** [comment]
Transaction.swift has added to the target.

**Comment by croath** [comment]
And these three files, too:
 - AnyCodable.swift
 - AnyDecodable.swift
 - AnyEncodable.swift

**Comment by zhenghongchuan** [comment]
Thanks! There are two points to note here.

1. The ZIP file that I download, "AnyCodable" folder is empty.

2. If use the OC, surround #import's with preprocessor directive #ifdef __OBJC__ #endif

**Comment by croath** [comment]
Thanks you again, @zhenghongchuan .

The "AnyCodable" is configured as a submodule, which could not be included when "downloading the zip archive file".
