### ISSUE TITLE
Mac project is ok, iOS project is not working...

### ISSUE THREAD

**Issue by MaoxinCao** [ProChain/SwiftyEOS#18]
``` javascript
let importedPk = try PrivateKey(keyString: "5HsaHvRCPrjU3yhapB5rLRyuKHuFTsziidA13Uw6WnQTeJAG3t4")
let importedPub = PublicKey(privateKey: importedPk!)
print("imported private key: \(importedPk!.wif())")
print("imported public key : \(importedPub.wif())")

var transfer = Transfer()
transfer.from = "raoji"
transfer.to = "raojiraoji12"
transfer.quantity = "1.0000 EOS"
transfer.memo = "test"

Currency.transferCurrency(transfer: transfer, code: "eosio.token", privateKey: importedPk!, completion: { (result, error) in
    if error != nil {
        if (error! as NSError).code == RPCErrorResponse.ErrorCode {
            print("\(((error! as NSError).userInfo[RPCErrorResponse.ErrorKey] as! RPCErrorResponse).errorDescription())")
        } else {
            print("other error: \(String(describing: error?.localizedDescription))")
        }
    } else {
        print("Ok. Txid: \(result!.transactionId)")
    }
})
```

Mac project is ok. iOS project can be signed but failed to pushTransaction.

I'm sure the privateKey and  transfer is correct. 

error:  RPCError(code: 3040000, name: "transaction_exception", what: "Transaction exception", details: [])

**Comment by croath** [comment]
The sample code uses a fake account `raoji`. The valid account length is 12.

**Comment by Pavan96** [comment]
Also need to update code in sample app as code: "eosio.token". Also have question how we can give user interface to user to get private key into app.

**Comment by croath** [comment]
`eosio.token` is the official token code.

If you're talking about generating key pairs or importing private keys, we provided ways for importing an existing one or generating a new one such as:

```swift
let importedPk = try PrivateKey(keyString: "5HsaHvRCPrjU3yhapB5rLRyuKHuFTsziidA13Uw6WnQTeJAG3t4")
```

If you're working on iOS, there's also helper classes and functions in `SEWallet.swift` with features like storing aes-encrypted keystores locally.
