### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by SteadyAction** [ProChain/SwiftyEOS#21]
Hello, this library looks very interesting and useful!
Thank you for the work.

I have several questions about how it works.

1. Does it fully work without downloading nodes? If so, how can it work without syncing nodes? 
2. Can I use this library using Cocoa Pods? I dont see any installation guides.

**Comment by croath** [comment]
Hi @SteadyAction ,

Thank you for giving SwiftyEOS a try!

1. Yes. It's a light(not equal to the `light` mode of EOS) wallet working without syncing node. Instead, the wallet works with an existing API endpoint. All the crypto part is done locally(on device) and the chain part is done by sending signed transaction via http rpc api. Queries about chain status are also done by rpc api.

2. No, not yet. I'll make it possible asap. Before that, just follow the steps in the readme file. Easy as it describes.
