### ISSUE TITLE
如何使用助记词

### ISSUE THREAD

**Issue by My-Old-Driver** [ProChain/SwiftyEOS#23]
如何使用助记词创建EOS的秘钥呢

**Comment by croath** [comment]
目前暂不支持助记词生成。BIP32/39/44 都不是为 EOS 设计的助记词生成算法，EOS 官方也从未缺省认同这些算法。如果要统一 key，并且使用 ETH 首选的 `m/44'/60'/0'/0/0` 路径，其实主要是还是为 private key 确认数据代替随机。

即使要加入这个功能，可能也会考虑加入从 binary data 生成 private key 的方法，而不是提供从助记词到私钥一步到位的方法。但不妨提供一些 helpers 来实现完整的助记词功能。

以上目前尚无开发计划。

**Comment by liunina** [comment]
> 目前暂不支持助记词生成。BIP32/39/44 都不是为 EOS 设计的助记词生成算法，EOS 官方也从未缺省认同这些算法。如果要统一 key，并且使用 ETH 首选的 `m/44'/60'/0'/0/0` 路径，其实主要是还是为 private key 确认数据代替随机。
> 
> 即使要加入这个功能，可能也会考虑加入从 binary data 生成 private key 的方法，而不是提供从助记词到私钥一步到位的方法。但不妨提供一些 helpers 来实现完整的助记词功能。
> 
> 以上目前尚无开发计划。

EOS由于历史原因起加密路径为"m/44'/194'/0'/0/0",只不过其没有地址概念,所谓的EOS pubkey是对标准算法得出的公钥进行特殊处理后加上前缀获得:

以下方法是根据[CoreBitcoin](https://github.com/oleganza/CoreBitcoin)框架根据 "m/44'/194'/0'/0/0"规则计算得到私钥对应的公钥计算EOS pubkey
仅供参考:

- (NSString*)toAddressWithExtPubKey:(NSData *)pubkeyData {
    
    NSData *checksum = BTCRIPEMD160(pubkeyData);
    
    NSMutableData *pub = [NSMutableData new];
    [pub appendData:pubkeyData];
    [pub appendData:[checksum subdataWithRange:NSMakeRange(0, 4)]];
    
    NSString *EOS_PREFIX = @"EOS";
    NSMutableString *address = [NSMutableString new];
    [address appendString:EOS_PREFIX];
    [address appendString:BTCBase58StringWithData(pub)];
    
    return address;
}

**Comment by croath** [comment]
@liunina Shall we add the feature into iOS helpers? We got 2 issues asking for mnemonic support.

**Comment by tidesnetwork** [comment]
Hi @croath It would be great if you can add this to iOS helpers.

**Comment by croath** [comment]
@tidesnetwork it's shipping on the way.

**Comment by ysoftware** [comment]
Is there a way to export existing private key as mnemonic string?

**Comment by croath** [comment]
@ysoftware I don't think it's possible. It's a one-way road from mnemonic to the private key.

**Comment by ysoftware** [comment]
@croath I'm sorry but it's not possible only with this approach or is it like this in all other blockchains?

**Comment by croath** [comment]
@ysoftware It's not about types of chains, but about the protocols they're using for key generating. From what I know, BIP39 protocol is not possible to do that. So it's not possible for ETH or EOS. But I don't know Bitcoin or other chains, cannot help you with that 😃 

Ref:

https://www.reddit.com/r/btc/comments/5zx6bw/converting_paperwallet_private_key_to_words/
https://bitcointalk.org/index.php?topic=1807217.0
https://bitcoin.stackexchange.com/questions/74568/private-key-to-mnemonic-words-is-it-safe
