### ISSUE TITLE
Cool !!!

### ISSUE THREAD

**Issue by RyanKung** [ProChain/SwiftyEOS#6]
@gitthanks send 10 ENU to @croath for this great work.

**Comment by gitthanks** [comment]
@RyanKung, you have bonus 10 ENU to @croath.

**Comment by croath** [comment]
Thanks for your support @RyanKung :shipit:

**Comment by gitthanks** [comment]
@RyanKung, you are not the member of [gitthanks.com](https://gitthanks.com) for now. Please login using github and deposit with [Bixin Crypto Wallet](https://bixin.im) first.
